
- name: Add z-push repo key
  apt_key:
    url: http://repo.z-hub.io/z-push:/final/Debian_9.0/Release.key
    state: present

- name: Add z-push repo
  apt_repository:
    repo: deb http://repo.z-hub.io/z-push:/final/Debian_9.0/ /
    state: present

- name: Update apt cache
  apt: update_cache=yes
  tags:
  - dependencies

- name: Install z-push and related packages
  apt: pkg={{ item }} state=installed
  with_items:
    - z-push-common
  tags:
    - dependencies

- name: Ensure z-push state and log directories are in place
  file: state=directory path={{ item }} owner=www-data group=www-data mode=0755
  with_items:
    - /decrypted/zpush-state
    - /var/log/z-push
  notify: restart apache

- name: Copy z-push's config.php into place
  template: src=usr_share_z-push_config.php.j2 dest=/usr/share/z-push/config.php
